### PR TITLE
Global-fix

### LINKED ISSUE #66: [Bug] Can't resolve 'global/window' error after updating to Storybook v7
### Describe the bug

I import the plugin in my `preview.js` with a simple import:

```
import '@storybook/addon-console';
```

It works fine for Storybook v6, but I'm getting an error after updating to v7.

### Expected behavior

The addon works with Storybook v7.

### Screenshots and/or logs

```
ERROR in ./node_modules/@storybook/addon-console/dist/index.js 8:37-61
Module not found: Error: Can't resolve 'global/window'
```

### Environment

 - Storybook version: v7.0.0-rc.7
 - OS: macOS
 - Node.js version: v18.15.0
 - NPM version: v8.19.4
 - Browser (if applicable): Chrome

### PR DESCRIPTION
**Pull request by unional**
fixes #66

### CODE REVIEW

**Comment by kasperpeulen** [comment]
cc @ndelangen

File: src/index.js [hunk 1]
```diff
@@ -90,7 +90,7 @@ function setScope(options) {
     if (toConsole.length) cLogger.error(...toConsole);
   };
 
-  window.onerror = (...args) => {
+  global.onerror = (...args) => {
```
Comment (ndelangen) [inline src/index.js:93]: This should really really use `addEventListener` instead of overriding `onerror`, because this destroys whatever `onerror` was before.

**Review by ndelangen — APPROVED** [review]
Change looks good, i think another huge improvement could be made, can happen in a separate PR,,

**Comment by unional** [comment]
Any update to this. It would be great to get this in and fix the global/window issue first and then tackle the overall improvement. thx.

**Comment by dbulnesInforma** [comment]
Great job, I am facing this issue since the new 7.0 release. My question is, once this is merged into master, should we just wait until having a new storybook-addon-console npm release? Thank you!

**Comment by unional** [comment]
Thanks for merging. Will the new version release anytime soon? thx

**Comment by dbulnesInforma** [comment]
I assume this project is deprecated because we have no new release. Thanks anyway for your efforts.

**Comment by ndelangen** [comment]
Sorry for the late reply, I was on vacation.

I just released v.2.0.0, making it compatible with storybook 7.0.0!
